### PR TITLE
Unlock files explicitly, scope checks and more

### PR DESCRIPTION
**Pull request by akhil1508**
This PR contains a bunch of different fixes to the app:

1) When a file is not downloaded from the Google Drive API for some reason(sometimes we have 403 forbidden responses), the files has to be deleted. 
  - During deletion, we see this error that causes the entire import to fail: `Google Drive import error: Unknow job failure. "File" is locked, existing lock on file: exclusive`
  - In the changes here, the file is explicitly unlocked before deletion so as to not cause issues with importing other files in the user's drive.

2) Scope checks from oauth redirect:
  - The scopes available to the access token are returned by the oauth redirect but they are not used currently
  - In the changes here, we are storing these scopes and using them to allow the user to import things accordingly
    - For example, if the user doesn't permit permissions to view and download photos, the "Import Photos" button is not displayed
    - Closes https://github.com/nextcloud/integration_google/issues/79

3) Google Drive allows files to have the same file name but Nextcloud doesn't. In order to ensure that files of the same also get downloaded(while maintaining a mapping between a file that has been imported and a file that is on Google Drive), we append the last 6 characters of the `fileItem` ID to the file name.
  - If the file with given file name already exists in the target directory of import, we check if the modified timestamp has changed and download it again from Google Drive if it has changed. This allows for resynch behavior

4) Many logger warnings have been removed as they contain information about the user's files and their metadata and this is a privacy concern. 

5) A new file called `failed-downloads.md` is created for Drive  imports in the user's chosen import directory. This contains a list of the files that failed to download for whatever reason.

### CODE REVIEW

**Comment by akhil1508** [comment]
@eneiluj WDYT?

**Comment by eneiluj** [comment]
@akhil1508 Wow thanks a lot for this big PR.

I agree with most of the changes.

1. Very nice. It would be even better to understand why some files are locked in the first place (and avoid it) but good enough.
2. :+1: Perfect!
3. I don't know about that one
* Having a non human readable suffix is not very nice
* This suffix is not unique for sure as it's just last 6 chars of the ID. Concatenation of the file name, the 6 char suffix and the file extension is most likely unique but not for sure :grin:.
Anyway let's keep it like that as it's still a big improvement.
4. Agreed but we could keep some privacy-friendly logs as they might be useful to debug future users issues.
5. :+1:

I'll make some adjustments (cosmetics, naming...) and merge this soon. Thanks again!

If you plan to make some other PRs, could you try to make them more atomic, to avoid including too many changes that are unrelated with each other?

**Comment by akhil1508** [comment]
@eneiluj 
About 3, even I felt a little uneasy with the renamed files and initally wanted to append "(2)", "(3)" and so on to the files with same names. But this would mean on each re-import, a file like "Untitled (3)" might become "Untitled (4)" causing confusion. 
The other way would be to store the file ids and their corresponding file names in an object in the user config. I didn't quite like this way as I don't want to keep the user's info on the db where the admin can see it(we already store token there though, perhaps we can improve this also..)

**Comment by akhil1508** [comment]
@eneiluj 
Makes sense about atomic PRs. I initially intended a PR with only the file unlocking fix. Then, while I was working on the problem of files not getting downloaded on a separate branch, the file unlocking problem kept blocking progress as it was throwing errors. 

Ultimately, I put everything into a single PR for everything but yes, I will keep in mind to create atomic PRs that are about a single concern.

**Comment by akhil1508** [comment]
BTW, another change in this PR was to check if the file is a document first and then check if it is other media. Quite a few documents actually have the `webContentLink` attribute set(at least in the accounts that I used for testing). If we check that first and try to download a document like it is media, we get 403s causing quite a few documents to not download correctly.

**Pull request merged**
