### PR TITLE
German: Language and Spelling Corrections

### PR DESCRIPTION
**Pull request by ancow**
Using the app I noticed some problems with the German translation. I corrected those and some I noticed directly in the language files.

### CODE REVIEW

**Comment by eneiluj** [comment]
Hi, thanks a lot. We actually manage translations on [Transifex](https://www.transifex.com/nextcloud/nextcloud/integration_google/). Could you apply your changes there?

**Comment by ancow** [comment]
> Hi, thanks a lot. We actually manage translations on [Transifex](https://www.transifex.com/nextcloud/nextcloud/integration_google/). Could you apply your changes there?

I just tried creating an account - it wants me to join as part of an organisation and tell them my phone number. So no.

**Comment by eneiluj** [comment]
I use my github account to authenticate there, no phone number given as far as i remember (I would have say no too :grin:).

**Comment by ancow** [comment]
That's what I did. After starting a "trial period" I was taken to a page with a bunch of personal data to fill in and no obvious way around that.
I now tried the link again and was taken to the Nextcloud project page, with a notification that I should "complete my profile". Not impressed by the UX...

I created suggestions for the German language changes. I couldn't figure out how to correct the `Goggle -> Google` thing in the `sl` files without claiming to speak Slovene (I *really* don't!), so didn't manage to add that correction.

Overall, for a one-off change, this workflow is *extremely* uncomfortable!

**Pull request closed without merging**
